#!/usr/bin/env perl
use v5.16;
use Mojolicious::Lite;

use DateTime;

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<header><h1>Calm Forest</h1></header>
<p>Welcome to the Mojolicious real-time web framework!</p>
<p>The time is now <% DateTime->now() %></p>
<footer><p>Inspired by <a href="http://myfico.com">myfico.com</a></p><p><a href="http://unvisited.com">Unvisited</a></footer>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    %= stylesheet '/d.css'
  </head>
  <body><%= content %>
<!-- AddThis Smart Layers BEGIN -->
<!-- Go to http://www.addthis.com/get/smart-layers to customize -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-531220e42ce608da"></script>
<script type="text/javascript">
    addthis.layers({
        'theme' : 'transparent',
        'share' : {
            'position' : 'left',
            'numPreferredServices' : 5
        }
    });
</script>
<!-- AddThis Smart Layers END -->
</body>
</html>
