#!/usr/bin/env perl
use v5.16;
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<header><h1>Calm Forest</h1></header>
<p>Welcome to the Mojolicious real-time web framework!</p>
<footer><p>Inspired by <a href="http://myfico.com">myfico.com</a></p></footer>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    %= stylesheet '/d.css'
  </head>
  <body><%= content %></body>
</html>
