#!/usr/bin/env perl
use v5.16;
use Mojolicious::Lite;

use DateTime;

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<header><h1>Calm Forest</h1></header>
<p>Welcome to the Mojolicious real-time web framework!</p>
<p>The time is now <%= DateTime->now() %></p>
<footer><p>Inspired by <a href="http://myfico.com">myfico.com</a></p><p><a href="http://unvisited.com">Unvisited</a></footer>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    %= stylesheet '/d.css'
  </head>
  <body><%= content %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48603515-1', 'calm-forest-8196.herokuapp.com');
  ga('send', 'pageview');

</script>
<!-- AddThis Smart Layers BEGIN -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-531220e42ce608da"></script>
<script type="text/javascript">
    addthis.layers({
        'theme' : 'transparent',
        'share' : {
            'position' : 'left',
            'numPreferredServices' : 5
        }
    });
</script>
<!-- AddThis Smart Layers END -->
</body>
</html>
